[package]
name = "hello_remote_world"
version = "0.1.0"
authors = ["VS Code <vscode@microsoft.com>"]
edition = "2018"

[dependencies]
yew = "0.11.0"

[lib]
path ="./src/lib/lib.rs"
crate-type = ["cdylib", "rlib"]
